#version: "3"

services:
  # Backend service (FastAPI)
  backend:
    image: samsung_oct_backend
    build: backend/
    ports:
      - 8000:8000
    networks:
      - project_network
    container_name: oct_backend
    volumes:
      - ./backend:/app/backend

  # Frontend service (Streamlit UI)
  frontend:
    image: samsung_oct_frontend
    build: frontend/
    depends_on:
      - backend
    ports:
      - 8501:8501
    networks:
      - project_network
    container_name: oct_frontend
    volumes:
      - ./frontend:/app/frontend

networks:
  project_network:
