version: "3"

services:
  backend:
    build: backend/
    ports:
      - 8000:8000
#    networks:
#      - deploy_network
    container_name: oct_backend

  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - 8501:8501
#    networks:
#      - deploy_network
    container_name: oct_frontend

#networks:
#  deploy_network:
#    driver: bridge  